// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (individual_holder_id, company_holder_id, holder_type)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateAccountParams struct {
	IndividualHolderID pgtype.UUID `json:"individual_holder_id"`
	CompanyHolderID    pgtype.UUID `json:"company_holder_id"`
	HolderType         HolderType  `json:"holder_type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.IndividualHolderID, arg.CompanyHolderID, arg.HolderType)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
