// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holders.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCompanyHolder = `-- name: CreateCompanyHolder :one
INSERT INTO company_holder (trade_name, cnpj, founded_at, corporate_email, phone, category, annual_revenue, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateCompanyHolderParams struct {
	TradeName      string              `json:"trade_name"`
	Cnpj           string              `json:"cnpj"`
	FoundedAt      pgtype.Date         `json:"founded_at"`
	CorporateEmail string              `json:"corporate_email"`
	Phone          string              `json:"phone"`
	Category       pgtype.Text         `json:"category"`
	AnnualRevenue  decimal.NullDecimal `json:"annual_revenue"`
	PasswordHash   []byte              `json:"password_hash"`
}

func (q *Queries) CreateCompanyHolder(ctx context.Context, arg CreateCompanyHolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCompanyHolder,
		arg.TradeName,
		arg.Cnpj,
		arg.FoundedAt,
		arg.CorporateEmail,
		arg.Phone,
		arg.Category,
		arg.AnnualRevenue,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createIndividualHolder = `-- name: CreateIndividualHolder :one
INSERT INTO individual_holder (full_name, cpf, date_of_birth, email, phone, category, monthly_income, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateIndividualHolderParams struct {
	FullName      string              `json:"full_name"`
	Cpf           string              `json:"cpf"`
	DateOfBirth   pgtype.Date         `json:"date_of_birth"`
	Email         string              `json:"email"`
	Phone         string              `json:"phone"`
	Category      pgtype.Text         `json:"category"`
	MonthlyIncome decimal.NullDecimal `json:"monthly_income"`
	PasswordHash  []byte              `json:"password_hash"`
}

func (q *Queries) CreateIndividualHolder(ctx context.Context, arg CreateIndividualHolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createIndividualHolder,
		arg.FullName,
		arg.Cpf,
		arg.DateOfBirth,
		arg.Email,
		arg.Phone,
		arg.Category,
		arg.MonthlyIncome,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCompanyHolderByEmail = `-- name: GetCompanyHolderByEmail :one
SELECT id, password_hash FROM company_holder WHERE corporate_email = $1
`

type GetCompanyHolderByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash []byte    `json:"password_hash"`
}

func (q *Queries) GetCompanyHolderByEmail(ctx context.Context, corporateEmail string) (GetCompanyHolderByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCompanyHolderByEmail, corporateEmail)
	var i GetCompanyHolderByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getIndividualHolderByEmail = `-- name: GetIndividualHolderByEmail :one
SELECT id, password_hash FROM individual_holder WHERE email = $1
`

type GetIndividualHolderByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash []byte    `json:"password_hash"`
}

func (q *Queries) GetIndividualHolderByEmail(ctx context.Context, email string) (GetIndividualHolderByEmailRow, error) {
	row := q.db.QueryRow(ctx, getIndividualHolderByEmail, email)
	var i GetIndividualHolderByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}
