// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AccountStatus string

const (
	AccountStatusActive AccountStatus = "active"
	AccountStatusClosed AccountStatus = "closed"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type HolderType string

const (
	HolderTypeIndividual HolderType = "individual"
	HolderTypeCompany    HolderType = "company"
)

func (e *HolderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HolderType(s)
	case string:
		*e = HolderType(s)
	default:
		return fmt.Errorf("unsupported scan type for HolderType: %T", src)
	}
	return nil
}

type NullHolderType struct {
	HolderType HolderType `json:"holder_type"`
	Valid      bool       `json:"valid"` // Valid is true if HolderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHolderType) Scan(value interface{}) error {
	if value == nil {
		ns.HolderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HolderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHolderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HolderType), nil
}

type TransactionType string

const (
	TransactionTypeDeposit     TransactionType = "deposit"
	TransactionTypeWithdrawal  TransactionType = "withdrawal"
	TransactionTypeTransferIn  TransactionType = "transfer_in"
	TransactionTypeTransferOut TransactionType = "transfer_out"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	ID                 uuid.UUID          `json:"id"`
	IndividualHolderID pgtype.UUID        `json:"individual_holder_id"`
	CompanyHolderID    pgtype.UUID        `json:"company_holder_id"`
	HolderType         HolderType         `json:"holder_type"`
	Balance            decimal.Decimal    `json:"balance"`
	Status             AccountStatus      `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
}

type CompanyHolder struct {
	ID             uuid.UUID           `json:"id"`
	TradeName      string              `json:"trade_name"`
	Cnpj           string              `json:"cnpj"`
	FoundedAt      pgtype.Date         `json:"founded_at"`
	CorporateEmail string              `json:"corporate_email"`
	Phone          string              `json:"phone"`
	Category       pgtype.Text         `json:"category"`
	AnnualRevenue  decimal.NullDecimal `json:"annual_revenue"`
	PasswordHash   []byte              `json:"password_hash"`
	CreatedAt      time.Time           `json:"created_at"`
}

type IndividualHolder struct {
	ID            uuid.UUID           `json:"id"`
	FullName      string              `json:"full_name"`
	Cpf           string              `json:"cpf"`
	DateOfBirth   pgtype.Date         `json:"date_of_birth"`
	Email         string              `json:"email"`
	Phone         string              `json:"phone"`
	Category      pgtype.Text         `json:"category"`
	MonthlyIncome decimal.NullDecimal `json:"monthly_income"`
	PasswordHash  []byte              `json:"password_hash"`
	CreatedAt     time.Time           `json:"created_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}
